# Generated by Django 3.1.14 on 2023-09-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MidiFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='midi_files/')),
            ],
        ),
        migrations.CreateModel(
            name='StaticMidiFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name1', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='midi_files/')),
            ],
        ),
    ]
