# Generated by Django 3.1.14 on 2023-09-28 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticmidifile',
            name='name1',
        ),
    ]
