# Generated by Django 3.1.14 on 2022-08-11 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PNC_Kids', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='picture',
        ),
        migrations.AddField(
            model_name='profile',
            name='ChildProfile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='IsChild',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='ParentProfile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='savings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=300)),
                ('cost', models.FloatField()),
                ('complete', models.BooleanField()),
                ('CreatedTime', models.DateTimeField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childGoals', to='PNC_Kids.profile')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parentGoals', to='PNC_Kids.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Chores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chore', models.CharField(max_length=300)),
                ('complete', models.BooleanField()),
                ('reward', models.FloatField()),
                ('CreatedTime', models.DateField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childChores', to='PNC_Kids.profile')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parentChores', to='PNC_Kids.profile')),
            ],
        ),
    ]
