# Generated by Django 3.1.14 on 2022-08-12 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PNC_Kids', '0002_auto_20220811_2350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='IsChild',
            new_name='isChild',
        ),
    ]
