# Generated by Django 3.1.14 on 2023-09-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_staticmidifile_name1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MidiFile',
        ),
        migrations.AddField(
            model_name='staticmidifile',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='staticmidifile',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
