# Generated by Django 3.1.14 on 2022-08-12 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PNC_Kids', '0003_auto_20220812_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
