# Generated by Django 3.1.14 on 2023-09-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230929_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='MidiFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='')),
                ('active', models.BooleanField(default=False)),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='StaticMidiFile',
        ),
    ]
