# Generated by Django 4.2.5 on 2023-10-03 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20230929_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midifile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
