# Generated by Django 3.1.14 on 2022-08-12 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PNC_Kids', '0004_profile_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chores',
            name='CreatedTime',
        ),
        migrations.RemoveField(
            model_name='goals',
            name='CreatedTime',
        ),
    ]
