# Generated by Django 4.1.7 on 2023-12-06 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_midifile_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrumEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField()),
                ('timing', models.FloatField()),
                ('midi_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strum_events', to='app.midifile')),
            ],
        ),
    ]
