# Generated by Django 3.1.14 on 2022-08-12 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PNC_Kids', '0005_auto_20220812_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chores',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='goals',
            name='pid',
        ),
    ]
