# Generated by Django 3.1.14 on 2022-08-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PNC_Kids', '0006_auto_20220812_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='savings',
            field=models.FloatField(default=0),
        ),
    ]
