# Generated by Django 3.1.14 on 2022-08-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PNC_Kids', '0008_auto_20220812_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chores',
            name='reward',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='goals',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
