# Generated by Django 3.1.14 on 2022-08-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PNC_Kids', '0009_auto_20220812_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chores',
            name='reward',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='goals',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='savings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
