# Generated by Django 3.1.14 on 2022-08-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PNC_Kids', '0010_auto_20220812_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
